name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Dry run (don't publish)"
        required: false
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  publish:
    name: Publish to npm/crates
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install

      - name: Build All
        run: npm run build

      # --- TypeScript ---
      - name: Publish typescript
        if: ${{ inputs.dry-run != true }}
        run: npm publish --access public
        working-directory: packages/eip7702
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish typescript (dry run)
        if: ${{ inputs.dry-run == true }}
        run: npm publish --access public --dry-run
        working-directory: packages/eip7702

      # --- Demo ---
      - name: Publish demo
        if: ${{ inputs.dry-run != true }}
        run: npm publish --access public
        working-directory: packages/demo
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish demo (dry run)
        if: ${{ inputs.dry-run == true }}
        run: npm publish --access public --dry-run
        working-directory: packages/demo

      # --- Dash ---
      - name: Publish dash
        if: ${{ inputs.dry-run != true }}
        run: npm publish --access public
        working-directory: packages/dash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish dash (dry run)
        if: ${{ inputs.dry-run == true }}
        run: npm publish --access public --dry-run
        working-directory: packages/dash
